name: docker-build-push

on: 
  workflow_run:
    workflows: ['golangci-lint']
    types: [completed]
    branches:
      - main
      
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Check repository
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
      - name: Build and push 
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: jovik31/go-backend:v${{ github.run_number}}
    
