name: docker-build-push

on: 
  workflow_run:
    workflows: ['golangci-lint']
    types: [completed]
    branches:
      - main
      
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Check repository
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
      - name: Build and push 
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: jovik31/go-backend:v${{ github.run_number}}
  modifygit:
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: change YAML deployment
        with:
          repository: 'jovik31/prod-cluster'
          token: ${{ secrets.PAT_GITHUB}}
      - name: configs
        run: |
          git config user.email joaogvicente@gmail.com
          git config user.name jovik31
          cd backend
          pwd
          cat deployment.yaml
      - name: change deployment
        uses: fjogeleit/yaml-update-action@main
        with:
          workDir: ./backend
          valueFile: 'deployment.yaml'
          propertyPath: 'spec.template.spec.containers.image'
          value: jovik31/go-backend:v${{github.run_number}}
          commitUSerName: jovik31
          commitUserEmail: ${{ secrets.EMAIL_GITHUB}}
          commitChange: true
          message: 'Automated by Github Actions: Changes by runner ${{ github.run_number }}'
            
        
          
            
  
    
