name: Build and Push Docker Image to Docker Hub

on: 
  push:
    branches:
      - main
      
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jovik31/go-backend:latest
    
