name: docker-build-push

on: 
  workflow_run:
    workflows: ['golangci-lint']
    types: [completed]
    branches:
      - main
      
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: jovik31/go-backend
          tags:
            type=semver, pattern={{major}}.{{minor}}
          
      - name: check repository
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
      - name: build and push 
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags}} , ${{ github.event.pull_request.head.sha }}
          labels: ${{ steps.meta.outputs.labels}}
    
