name: "Docker build"

on: 
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Build
        run: make docker-build
    
