name: docker-build-push

on: 
  workflow_run:
    workflows: ['golangci-lint']
    types: [completed]
    branches:
      - main
    tags:
      - 'v*'
      
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: jovik31/go-backend
          
      - name: check repository
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
      - name: build and push 
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name 1= 'pull_request'}}
          tags: ${{ steps.meta.outputs.tags}}
          labels: ${{ steps.meta.outputs.labels}}
          file: ./Dockerfile
          push: true
          tags: jovik31/go-backend:latest
    
